// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYaZPhfLZ3059e-fRJPeNKF0KpAT74YJQ',
    appId: '1:684921697259:web:739ebb98ac4f479dd99fae',
    messagingSenderId: '684921697259',
    projectId: 'bloc-auth-flow-2c82f',
    authDomain: 'bloc-auth-flow-2c82f.firebaseapp.com',
    storageBucket: 'bloc-auth-flow-2c82f.appspot.com',
    measurementId: 'G-1S1EYK1TP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATFcOZh6kOj8bCzD7RiYzkQuXbcOoOCdA',
    appId: '1:684921697259:android:19e4493cee21c594d99fae',
    messagingSenderId: '684921697259',
    projectId: 'bloc-auth-flow-2c82f',
    storageBucket: 'bloc-auth-flow-2c82f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6nP5pkxY1di29PV3GJENh_4ZcQwBIeq0',
    appId: '1:684921697259:ios:337c98d7217d9bdad99fae',
    messagingSenderId: '684921697259',
    projectId: 'bloc-auth-flow-2c82f',
    storageBucket: 'bloc-auth-flow-2c82f.appspot.com',
    iosBundleId: 'com.example.blocAuthFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6nP5pkxY1di29PV3GJENh_4ZcQwBIeq0',
    appId: '1:684921697259:ios:b14b33605921dd07d99fae',
    messagingSenderId: '684921697259',
    projectId: 'bloc-auth-flow-2c82f',
    storageBucket: 'bloc-auth-flow-2c82f.appspot.com',
    iosBundleId: 'com.example.blocAuthFlow.RunnerTests',
  );
}
